# Generated by Django 2.2.10 on 2021-06-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdb', '0003_auto_20210630_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltag',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_name', to='cdb.GlobalTagStatus'),
        ),
    ]
