# Generated by Django 2.2.10 on 2021-06-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdb', '0004_auto_20210630_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltag',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdb.GlobalTagStatus'),
        ),
    ]
